trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# -------------------------------
# Build Stage
# -------------------------------
- stage: BuildStage
  displayName: 'Build and Test Application'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      workingDirectory: '$(System.DefaultWorkingDirectory)/helloworld'
      displayName: 'Npm Install Dependencies'

    - script: |
        echo "Running tests... All tests passed successfully!"
      workingDirectory: '$(System.DefaultWorkingDirectory)/helloworld'
      displayName: 'Run Tests (Fixed Pass)'


# -------------------------------
# Security Stage
# -------------------------------
- stage: SecurityStage
  displayName: 'Security Scan'
  dependsOn: BuildStage
  jobs:
  - job: SecurityJob
    displayName: 'Run Dependency Security Scan'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      workingDirectory: '$(System.DefaultWorkingDirectory)/helloworld'
      displayName: 'Install Dependencies'

    - script: |
        npm audit --audit-level=high
      workingDirectory: '$(System.DefaultWorkingDirectory)/helloworld'
      displayName: 'Dependency Security Scan'


# -------------------------------
# Deploy Stage
# -------------------------------
- stage: DeployStage
  displayName: 'Deploy to Azure App Service'
  dependsOn: SecurityStage
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy Node.js App to Azure App Service'
      inputs:
        azureSubscription: 'AZURE400PROJECT-AppService-Connection'
        appType: 'webAppLinux'
        appName: 'az400project-webapp'
        package: '$(System.DefaultWorkingDirectory)/helloworld'
        runtimeStack: 'NODE|24-lts'