trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildStage
  displayName: 'Build and Test Application'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      workingDirectory: '$(System.DefaultWorkingDirectory)/helloworld'
      displayName: 'Npm Install Dependencies'

    - script: |
        npm test
      workingDirectory: '$(System.DefaultWorkingDirectory)/helloworld'
      displayName: 'Run Tests (Intentional Failure)'